"""Write frameworks/base/config/hiddenapi-whitelist.txt from factory hidden-API flags.

Takes compare-pico-api.py --hiddenapi --json reports and lists every member that the
factory framework.jar marks WHITELIST while the Source build does not, plus the PICO
Manifest.permission constants whose factory flag is WHITELIST. Usage:
  python tools/generate-pico-hiddenapi.py --compare <report.json>... --out <hiddenapi-whitelist.txt>
"""
import argparse
import json
from pathlib import Path

# android.Manifest.permission fields that are WHITELIST in the factory framework.jar.
PERMISSIONS = ['Landroid/Manifest$permission;->POWER_SCENE_CHANGE:Ljava/lang/String;',
               'Landroid/Manifest$permission;->lifecycle:Ljava/lang/String;',
               'Landroid/Manifest$permission;->startevent:Ljava/lang/String;']
HEADER = ['# Non-SDK members that PICO OS 5.13.7 exposes to applications (hidden-API whitelist).',
          '# Generated by tools/generate-pico-hiddenapi.py from the factory framework.jar flags.']


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--compare', type=Path, nargs='+', required=True)
    parser.add_argument('--out', type=Path, required=True)
    args = parser.parse_args()
    entries = set(PERMISSIONS)
    for path in args.compare:
        for row in json.loads(path.read_text())['rows']:
            for difference in row['differences']:
                if isinstance(difference, dict) and difference.get('factory') == 'WHITELIST' \
                        and 'hiddenapi' in difference:
                    entries.add(difference['hiddenapi'])
    args.out.write_text('\n'.join(HEADER + sorted(entries)) + '\n', newline='\n')
    print('%d whitelist entries' % len(entries))


if __name__ == '__main__':
    main()
