"""Reconstruct the PICO/OEM part of the factory 5.13.7 platform SELinux policy.

The factory system image ships only the compiled plat_sepolicy.cil. This tool
subtracts the Source baseline (AOSP android-10.0.0_r47 system/sepolicy plus
CodeLinaro device/qcom/sepolicy generic+qva, built without the device policy)
and writes the remaining factory declarations, rules and contexts as policy
sources.

Declarations are placed where the factory built them. The compiled CIL keeps
the source order of type/attribute declarations (system/sepolicy public,
CodeLinaro generic/qva public, the PICO device public dir, then the same for
private), so each reconstructed declaration goes to system/sepolicy (a patch,
mirrored into prebuilts/api/29.0 for the freeze test) or to
device/pico/PICOA8110/sepolicy. A system/sepolicy declaration only names
system/sepolicy attributes, so the base platform policy still compiles alone.
All rules, remaining memberships, transitions, genfscon and contexts are
written to device/pico/PICOA8110/sepolicy/{public,private}.

Visibility follows the factory: a type is public iff the factory
mapping/29.0.cil maps it; an attribute, attribute membership or rule is public
iff the factory vendor plat_pub_versioned.cil (the factory public policy as
seen by vendor) contains it. Neverallow rules are reconstructed only when they
name a reconstructed type or attribute; neverallows that differ only in their
AOSP exception lists are system/sepolicy changes (patches), see
tools/check-sepolicy.py.

Run inside WSL. Reads only; writes the generated files and
validation/sepolicy-reconstruction.json.
"""
import collections
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from sepolicy_cil import (AUTO_ATTRIBUTE, Policy, flatten, mapping_sets, parse,  # noqa: E402
                          te_name)

ROOT = Path(__file__).resolve().parents[1]
PROJECT = Path('/mnt/wsl/PHYSICALDRIVE5p3/home/red_panda/RedPandaAndroid/pico4-pro')
FACTORY = PROJECT / 'analysis/stock-5.13.7-system/root/system/etc/selinux'
VENDOR = PROJECT / 'analysis/stock-5.13.7-partitions/vendor/etc/selinux'
BASELINE = PROJECT / 'analysis/sepolicy-source-baseline'
SOURCE = PROJECT / 'source/aosp-10'
OUT = ROOT / 'device/pico/PICOA8110/sepolicy'
SEPOLICY = SOURCE / 'system/sepolicy'
SEGMENT_DIRS = {
    'aosp_public': 'system/sepolicy/public', 'aosp_private': 'system/sepolicy/private',
    'generic_public': 'device/qcom/sepolicy/generic/public',
    'qva_public': 'device/qcom/sepolicy/qva/public',
    'generic_private': 'device/qcom/sepolicy/generic/private',
    'qva_private': 'device/qcom/sepolicy/qva/private',
}
VERSION = '29_0'
HEADER = ('# Generated by tools/reconstruct-factory-sepolicy.py from the factory PICO 5.13.7\n'
          '# plat_sepolicy.cil minus AOSP android-10.0.0_r47 and CodeLinaro\n'
          '# device/qcom/sepolicy 830b6eb9 (generic + qva). Do not edit by hand.\n')
CONTEXTS = {'file': 'file_contexts', 'property': 'property_contexts',
            'service': 'service_contexts', 'hwservice': 'hwservice_contexts'}


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def contexts_lines(path, kind):
    lines = {}
    for raw in path.read_text().splitlines():
        line = raw.split('#', 1)[0].strip()
        if not line:
            continue
        fields = line.split()
        key = ' '.join(fields[:-1]) if kind == 'file' else fields[0]
        lines[key] = raw.strip()
    return lines


def known_declarations():
    """Directory segment of every type/attribute declared in the Source policy dirs."""
    types, attributes = {}, {}
    for segment, directory in SEGMENT_DIRS.items():
        for path in sorted((SOURCE / directory).glob('*')):
            if not (path.suffix == '.te' or path.name == 'attributes'):
                continue
            if path.name == 'pico_factory.te':
                continue
            text = path.read_text()
            for match in re.finditer(r'^\s*type\s+([\w-]+)', text, re.M):
                types.setdefault(match.group(1), segment)
            for match in re.finditer(r'^\s*attribute\s+([\w-]+)', text, re.M):
                attributes.setdefault(match.group(1), segment)
            for match in re.finditer(r'^\s*hal_attribute\((\w+)\)', text, re.M):
                for suffix in ('', '_client', '_server'):
                    attributes.setdefault('hal_' + match.group(1) + suffix, segment)
    return types, attributes


def segments(order, known, new):
    """Factory source segment of each new name from its declaration neighbours."""
    placed = {}
    for index, name in enumerate(order):
        if name not in new:
            continue
        before = next((known[n] for n in reversed(order[:index]) if n in known), None)
        after = next((known[n] for n in order[index + 1:] if n in known), None)
        if before is None:
            raise RuntimeError('No declaration before ' + name)
        if before == after or before.startswith('aosp_'):
            placed[name] = before
        else:
            # After the last CodeLinaro declaration of a public/private run:
            # the PICO device directory that follows it.
            placed[name] = 'device_' + before.split('_')[1]
    return placed


def deversion(text, public_types):
    def replace(match):
        base = match.group(1)
        return base if base in public_types else match.group(0)
    return re.sub(r'([A-Za-z0-9_.-]+)_' + VERSION + r'\b', replace, text)


class PublicView:
    """Factory public policy as vendor sees it, with version suffixes removed."""

    def __init__(self, policy, public_types):
        self.attributes = {deversion(a, public_types) for a in policy.attributes
                           if not a.endswith('_' + VERSION) and not AUTO_ATTRIBUTE.match(a)}
        self.membership = {(deversion(t, public_types), a) for t, a in policy.membership()}
        self.rules = {tuple(deversion(x, public_types) for x in rule) for rule in policy.rule_set()}
        self.xrules = {tuple(deversion(x, public_types) for x in rule) for rule in policy.xrule_set()}
        self.transitions = {tuple(deversion(x, public_types) for x in t)
                            for t in policy.transition_set()}


def positive_names(te):
    """Names a te type set grants to (not the '-name' exceptions or '~{ }' parts)."""
    if te.startswith('~'):
        return set()
    return {token for token in te.replace('{', ' ').replace('}', ' ').split()
            if not token.startswith('-')}


def te_rule(kind, src, tgt, cls, perms):
    keyword = {'allow': 'allow', 'auditallow': 'auditallow', 'dontaudit': 'dontaudit',
               'neverallow': 'neverallow'}[kind]
    body = perms[0] if len(perms) == 1 else '{ ' + ' '.join(perms) + ' }'
    return '%s %s %s:%s %s;' % (keyword, src, tgt, cls, body)


def te_xrule(kind, src, tgt, spec):
    node = parse(spec)[0]           # (ioctl class (values...))
    operation, cls, values = node[0], node[1], node[2]
    parts = []
    for value in values:
        if isinstance(value, list):
            if value[0] != 'range':
                raise ValueError('Unsupported xperm ' + spec)
            parts.append(value[1] + '-' + value[2])
        else:
            parts.append(value)
    keyword = {'allowx': 'allowxperm', 'auditallowx': 'auditallowxperm',
               'dontauditx': 'dontauditxperm', 'neverallowx': 'neverallowxperm'}[kind]
    body = parts[0] if len(parts) == 1 else '{ ' + ' '.join(parts) + ' }'
    return '%s %s %s:%s %s %s;' % (keyword, src, tgt, cls, operation, body)


def te_transition(item):
    kind, src, tgt, cls = item[0], item[1], item[2], item[3]
    keyword = {'typetransition': 'type_transition', 'typechange': 'type_change',
               'typemember': 'type_member'}[kind]
    if len(item) == 6:
        return '%s %s %s:%s %s %s;' % (keyword, src, tgt, cls, item[5], item[4])
    return '%s %s %s:%s %s;' % (keyword, src, tgt, cls, item[4])


def main():
    if sys.platform != 'linux':
        raise RuntimeError('Run inside WSL')
    volume = subprocess.check_output(['findmnt', '-n', '-o', 'FSTYPE,UUID', '--target',
                                      str(PROJECT)], text=True).split()
    if volume != ['ext4', 'a00da05f-1eb2-44b6-99f0-9109391f67dc']:
        raise RuntimeError('Expected ext4 source volume')

    factory = Policy((FACTORY / 'plat_sepolicy.cil').read_text())
    source = Policy((BASELINE / 'plat_sepolicy.cil').read_text())
    factory_mapping = mapping_sets((FACTORY / 'mapping/29.0.cil').read_text())
    public_types = {t for members in factory_mapping.values() for t in members}
    public = PublicView(Policy((VENDOR / 'plat_pub_versioned.cil').read_text()), public_types)

    new_types = factory.types - source.types
    factory_attributes = {a for a in factory.attributes if not AUTO_ATTRIBUTE.match(a)}
    source_attributes = {a for a in source.attributes if not AUTO_ATTRIBUTE.match(a)}
    new_attributes = factory_attributes - source_attributes
    new_names = new_types | new_attributes

    # te spelling of every normalized factory type set.
    spelling = {}
    for name in factory.types | factory.attributes | {'self'}:
        spelling[factory.norm(name)] = te_name(factory, name)

    sections = {'public': collections.defaultdict(list), 'private': collections.defaultdict(list)}
    counts = collections.Counter()

    factory_statements = parse((FACTORY / 'plat_sepolicy.cil').read_text())
    type_order = [x[1] for x in factory_statements if x[0] == 'type']
    attribute_order = [x[1] for x in factory_statements if x[0] == 'typeattribute']
    known_types, known_attributes = known_declarations()
    type_segment = segments(type_order, known_types, new_types)
    attribute_segment = segments(attribute_order, known_attributes, new_attributes)
    aosp_attributes = {a for a, seg in known_attributes.items() if seg.startswith('aosp_')}
    aosp_attributes |= {a for a, seg in attribute_segment.items() if seg.startswith('aosp_')}
    sepolicy_sections = {'public': collections.defaultdict(list),
                         'private': collections.defaultdict(list)}
    placement = collections.Counter()

    def target(segment, side):
        if segment.startswith('aosp_'):
            if segment != 'aosp_' + side:
                raise RuntimeError('Visibility differs from the factory segment')
            return sepolicy_sections[side]
        if not segment.startswith('device_'):
            raise RuntimeError('Declaration inside a CodeLinaro run: ' + segment)
        return sections[side]

    # Attributes.
    for attribute in sorted(new_attributes):
        side = 'public' if attribute in public.attributes else 'private'
        section = target(attribute_segment[attribute], side)
        section['attributes'].append('attribute %s;' % attribute)
        if attribute in factory.expand:
            section['attributes'].append('expandattribute %s %s;' % (
                attribute, factory.expand[attribute]))
        counts[side + '_attributes'] += 1
        placement[attribute_segment[attribute]] += 1

    # Types with their attribute memberships.
    new_membership = factory.membership() - source.membership()
    inline_done = set()
    for name in sorted(new_types):
        side = 'public' if name in public_types else 'private'
        segment = type_segment[name]
        section = target(segment, side)
        inline = sorted(a for t, a in new_membership if t == name and
                        (side == 'private' or (t, a) in public.membership) and
                        (segment.startswith('device_') or a in aosp_attributes))
        inline_done.update((name, a) for a in inline)
        section['types'].append('type %s;' % ', '.join([name] + inline))
        counts[side + '_types'] += 1
        placement[segment] += 1
    # Remaining memberships: existing types, public types in private attributes,
    # system/sepolicy types in attributes declared outside system/sepolicy.
    # A system/sepolicy type keeps its system/sepolicy attributes there (the
    # base platform policy needs e.g. coredomain); other memberships go to the
    # device policy.
    for name, attribute in sorted(new_membership - inline_done):
        side = 'public' if name in public_types and (name, attribute) in public.membership \
            else 'private'
        if type_segment.get(name, '').startswith('aosp_') and attribute in aosp_attributes:
            if side == 'public':
                raise RuntimeError('Public membership left over: %s %s' % (name, attribute))
            sepolicy_sections['private']['typeattributes'].append(
                'typeattribute %s %s;' % (name, attribute))
        else:
            sections[side]['typeattributes'].append('typeattribute %s %s;' % (name, attribute))
        counts[side + '_memberships'] += 1

    # Rules.
    grouped = collections.defaultdict(set)
    skipped_neverallow = 0
    for rule in factory.rule_set() - source.rule_set():
        kind, src, tgt, cls, perm = rule
        if kind == 'neverallow' and not ((positive_names(spelling[src]) |
                                          positive_names(spelling[tgt])) & new_names):
            skipped_neverallow += 1
            continue
        side = 'public' if rule in public.rules else 'private'
        grouped[(side, kind, src, tgt, cls)].add(perm)
    for (side, kind, src, tgt, cls), perms in sorted(grouped.items()):
        source_set = spelling[src]
        target_set = spelling[tgt]
        if kind == 'neverallow' and cls == 'process' and perms == {'ptrace'} and \
                source_set == '{ domain %s }' % ' '.join(
                    '-' + n for n in sorted({'crash_dump', 'runas_app', target_set})):
            # app_domain() ptrace neverallow; the factory is a user build, the
            # macro also exempts llkd on userdebug/eng.
            source_set = "{ domain -%s -crash_dump userdebug_or_eng(`-llkd') -runas_app }" % \
                target_set
        sections[side]['rules'].append(te_rule(kind, source_set, target_set, cls,
                                               sorted(perms)))
        counts[side + '_' + kind] += len(perms)
    for rule in sorted(factory.xrule_set() - source.xrule_set()):
        kind, src, tgt, spec = rule
        if kind == 'neverallowx' and not ((positive_names(spelling[src]) |
                                           positive_names(spelling[tgt])) & new_names):
            skipped_neverallow += 1
            continue
        side = 'public' if rule in public.xrules else 'private'
        sections[side]['xrules'].append(te_xrule(kind, spelling[src], spelling[tgt], spec))
        counts[side + '_' + kind] += 1
    for item in sorted(factory.transition_set() - source.transition_set()):
        side = 'public' if item in public.transitions else 'private'
        spelled = (item[0], spelling[item[1]], spelling[item[2]]) + item[3:]
        sections[side]['transitions'].append(te_transition(spelled))
        counts[side + '_' + item[0]] += 1

    # genfs labels.
    genfs = []
    for (fs, path), label in sorted(factory.genfs.items()):
        if source.genfs.get((fs, path)) != label:
            if (fs, path) in source.genfs:
                raise RuntimeError('Conflicting genfscon ' + fs + ' ' + path)
            genfs.append('genfscon %s %s u:object_r:%s:s0' % (fs, path, label))

    # Contexts files.
    contexts = {}
    for kind, name in CONTEXTS.items():
        theirs = contexts_lines(FACTORY / ('plat_' + name), kind)
        ours = contexts_lines(BASELINE / ('plat_' + name), kind)
        extra = []
        for key, line in theirs.items():
            if key in ours:
                if ours[key].split()[-1 if kind == 'file' else 1] != line.split()[-1 if kind == 'file' else 1]:
                    raise RuntimeError('Conflicting %s context for %s' % (kind, key))
                continue
            extra.append(line)
        contexts[name] = extra

    # Write.
    written = {}
    for side in ('public', 'private'):
        directory = OUT / side
        directory.mkdir(parents=True, exist_ok=True)
        section = sections[side]
        if section['attributes']:
            text = HEADER + '\n' + '\n'.join(section['attributes']) + '\n'
            (directory / 'attributes').write_text(text)
            written[side + '/attributes'] = text
        body = []
        for title, key in (('Types', 'types'), ('Attribute memberships', 'typeattributes'),
                           ('Type transitions', 'transitions'), ('Rules', 'rules'),
                           ('Extended permission rules', 'xrules')):
            if section[key]:
                body.append('# ' + title)
                body.extend(section[key])
                body.append('')
        if body:
            text = HEADER + '\n' + '\n'.join(body)
            (directory / 'pico_factory.te').write_text(text)
            written[side + '/pico_factory.te'] = text
    for side in ('public', 'private'):
        section = sepolicy_sections[side]
        body = []
        for title, key in (('Attributes', 'attributes'), ('Types', 'types'),
                           ('Attribute memberships', 'typeattributes')):
            if section[key]:
                body.append('# ' + title)
                body.extend(section[key])
                body.append('')
        path = Path(side) / 'pico_factory.te'
        if body:
            text = HEADER + '\n' + '\n'.join(body)
            for base in (SEPOLICY, SEPOLICY / 'prebuilts/api/29.0'):
                (base / path).write_text(text)
            written['system/sepolicy/' + str(path)] = text
    # New public system/sepolicy types have no 28.0 analogue (treble compat test).
    new_objects = sorted(n for n, seg in type_segment.items() if seg == 'aosp_public')
    marker = '    ;; PICO 5.13.7 factory platform types (tools/reconstruct-factory-sepolicy.py)\n'
    for base in (SEPOLICY, SEPOLICY / 'prebuilts/api/29.0'):
        path = base / 'private/compat/28.0/28.0.ignore.cil'
        text = path.read_text()
        if marker in text:
            text = text[:text.index(marker)].rstrip('\n') + '))\n'
        if not text.endswith('))\n'):
            raise RuntimeError('Unexpected end of ' + str(path))
        text = text[:-3] + '\n' + marker + ''.join('    %s\n' % n for n in new_objects)
        text = text.rstrip('\n') + '))\n'
        path.write_text(text)
    if genfs:
        text = HEADER + '\n' + '\n'.join(genfs) + '\n'
        (OUT / 'private/genfs_contexts').write_text(text)
        written['private/genfs_contexts'] = text
    for name, lines in contexts.items():
        if lines:
            text = HEADER + '\n' + '\n'.join(lines) + '\n'
            (OUT / 'private' / name).write_text(text)
            written['private/' + name] = text

    report = {
        'inputs': {
            'factory_plat_sepolicy': {'path': str(FACTORY / 'plat_sepolicy.cil'),
                                      'sha256': sha256(FACTORY / 'plat_sepolicy.cil')},
            'factory_mapping': {'path': str(FACTORY / 'mapping/29.0.cil'),
                                'sha256': sha256(FACTORY / 'mapping/29.0.cil')},
            'factory_plat_pub_versioned': {'path': str(VENDOR / 'plat_pub_versioned.cil'),
                                           'sha256': sha256(VENDOR / 'plat_pub_versioned.cil')},
            'source_baseline': {'path': str(BASELINE / 'plat_sepolicy.cil'),
                                'sha256': sha256(BASELINE / 'plat_sepolicy.cil'),
                                'content': 'AOSP android-10.0.0_r47 system/sepolicy + CodeLinaro '
                                           'device/qcom/sepolicy 830b6eb9 generic/qva public+private, '
                                           'without device/pico policy'},
        },
        'reconstructed': {
            'types': len(new_types), 'public_types': len(new_types & public_types),
            'attributes': len(new_attributes),
            'counts': dict(sorted(counts.items())),
            'declaration_segments': dict(sorted(placement.items())),
            'genfscon': len(genfs),
            'contexts': {name: len(lines) for name, lines in contexts.items()},
            'neverallow_exception_list_changes_not_reconstructed': skipped_neverallow,
        },
        'files': {name: {'sha256': hashlib.sha256(text.encode()).hexdigest(),
                         'lines': text.count('\n')} for name, text in sorted(written.items())},
    }
    (ROOT / 'validation/sepolicy-reconstruction.json').write_text(json.dumps(report, indent=2) + '\n')
    print(json.dumps(report['reconstructed'], indent=2))


if __name__ == '__main__':
    main()
