"""Actual actuator shutdown/open/last-close and native release phase reuse."""
from pathlib import Path
import hashlib,json,subprocess,importlib.util
BASE=Path('/mnt/wsl/PHYSICALDRIVE5p3/home/red_panda/RedPandaAndroid/pico4-pro');SOURCE=BASE/'source/phoenix-kernel-recovery';D='techpack/camera/drivers/cam_sensor_module/cam_actuator/'
MAIN=r'''
static void run_shutdown(struct cam_actuator_ctrl_t *ctrl){mutex_lock(&ctrl->actuator_mutex);cam_actuator_shutdown(ctrl);mutex_unlock(&ctrl->actuator_mutex);}
int main(void){
 struct cam_actuator_ctrl_t ctrl={.actuator_mutex={PTHREAD_MUTEX_INITIALIZER},.bridge_intf={-1,-1,-1,0}};expected_owner=&ctrl;struct v4l2_subdev sd={&ctrl};run_shutdown(&ctrl);assert(!powers&&!destroys&&!frees);
 ctrl.bridge_intf.device_hdl=1234;ctrl.bridge_intf.session_hdl=41;ctrl.pico_acquire_cleanup_pending=true;destroy_error=-EIO;
 assert(!cam_actuator_subdev_open(&sd,NULL)&&!cam_actuator_subdev_open(&sd,NULL));assert(!cam_actuator_subdev_close(&sd,NULL)&&ctrl.open_cnt==1&&!destroys);assert(!cam_actuator_subdev_close(&sd,NULL)&&ctrl.open_cnt==0&&destroys==1&&ctrl.pico_acquire_cleanup_pending&&ctrl.bridge_intf.device_hdl==1234&&!powers&&!frees);assert(cam_actuator_subdev_close(&sd,NULL)==-EINVAL&&destroys==1);
 destroy_error=0;assert(!cam_actuator_subdev_open(&sd,NULL)&&!cam_actuator_subdev_close(&sd,NULL));assert(!ctrl.pico_acquire_cleanup_pending&&ctrl.bridge_intf.device_hdl==-1&&!powers&&!frees);
 struct cam_actuator_soc_private soc={0};ctrl.soc_info.soc_private=&soc;soc.power_info.power_setting=malloc(8);soc.power_info.power_down_setting=malloc(8);soc.power_info.power_setting_size=soc.power_info.power_down_setting_size=1;ctrl.bridge_intf.device_hdl=1234;ctrl.bridge_intf.session_hdl=41;ctrl.bridge_intf.link_hdl=7;ctrl.cam_act_state=CAM_ACTUATOR_START;power_error=-EIO;unsigned before=destroys;
 run_shutdown(&ctrl);assert(powers==1&&destroys==before&&!frees&&ctrl.cam_act_state==CAM_ACTUATOR_START&&ctrl.pico_release_cleanup_pending&&!ctrl.pico_release_power_done&&ctrl.bridge_intf.device_hdl==1234&&soc.power_info.power_setting);
 power_error=0;destroy_error=-EAGAIN;run_shutdown(&ctrl);assert(powers==2&&destroys==before+1&&!frees&&ctrl.cam_act_state==CAM_ACTUATOR_ACQUIRE&&ctrl.pico_release_power_done&&ctrl.bridge_intf.link_hdl==7);run_shutdown(&ctrl);assert(powers==2&&destroys==before+2&&!frees);
 destroy_error=0;run_shutdown(&ctrl);assert(powers==2&&frees==2&&ctrl.cam_act_state==CAM_ACTUATOR_INIT&&ctrl.bridge_intf.device_hdl==-1&&ctrl.bridge_intf.link_hdl==-1&&!ctrl.pico_release_cleanup_pending&&!ctrl.pico_release_power_done&&!soc.power_info.power_setting&&!soc.power_info.power_down_setting&&!soc.power_info.power_setting_size&&!soc.power_info.power_down_setting_size);before=destroys;run_shutdown(&ctrl);assert(destroys==before&&powers==2&&frees==2);
 ctrl.bridge_intf.device_hdl=1234;ctrl.bridge_intf.session_hdl=41;ctrl.cam_act_state=CAM_ACTUATOR_CONFIG;destroy_error=-EIO;struct cam_control cmd={.op_code=CAM_RELEASE_DEV,.handle_type=CAM_HANDLE_USER_POINTER};assert(cam_actuator_driver_cmd(&ctrl,&cmd)==-EIO&&powers==3&&ctrl.pico_release_power_done);destroy_error=0;run_shutdown(&ctrl);assert(powers==3&&ctrl.cam_act_state==CAM_ACTUATOR_INIT&&!ctrl.pico_release_power_done&&!ctrl.pico_release_cleanup_pending);
 assert(!held);assert(!pthread_mutex_destroy(&ctrl.actuator_mutex.value));puts("PASS: actual actuator shutdown/open/last-close/native release; pending INIT without soc dereference, close count/reopen retry, forced START/linked close, power/handle failures retain resources, reported power stage not repeated, native-release to shutdown reuse, final cleanup once");
}
'''
def main():
    spec=importlib.util.spec_from_file_location('acquire',Path(__file__).with_name('test-pico-actuator-acquire-retry.py'));m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
    extractor=m.load('test-pico-sensor-mono-hook');core=(SOURCE/D/'cam_actuator_core.c').read_text();dev=(SOURCE/D/'cam_actuator_dev.c').read_text()
    code=m.make_code(MAIN).replace('static void kfree(void *p){assert(!p);}','static unsigned frees;static void kfree(void *p){if(p){frees++;free(p);}}').replace('unsigned last_flush_req;','unsigned last_flush_req,open_cnt;').replace('struct v4l2_subdev {int marker;};','struct v4l2_subdev {struct cam_actuator_ctrl_t *ctrl;};')
    extra='struct v4l2_subdev_fh {int unused;};\nstatic void *v4l2_get_subdevdata(struct v4l2_subdev *sd){return sd->ctrl;}\n'+extractor.function(core,'void cam_actuator_shutdown(')+extractor.function(dev,'static int cam_actuator_subdev_open(')+extractor.function(dev,'static int cam_actuator_subdev_close(')
    code=code.replace(MAIN,extra+MAIN);out=BASE/'out/phoenix-kernel-recovery/actuator-shutdown-retry-tests';out.mkdir(exist_ok=True);(out/'harness.c').write_text(code)
    subprocess.run(['gcc','-std=gnu11','-g','-O1','-pthread','-fsanitize=address,undefined','-fno-omit-frame-pointer','-I'+str(SOURCE/'techpack/camera/include/uapi/media'),'-I'+str(SOURCE/'techpack/camera/include/uapi'),str(out/'harness.c'),'-o',str(out/'test')],check=True)
    r=subprocess.run([str(out/'test')],capture_output=True,text=True,timeout=10);report={'sources':{n:hashlib.sha256((SOURCE/n).read_bytes()).hexdigest() for n in [*m.NAMES,D+'cam_actuator_dev.c']},'harness_sha256':hashlib.sha256(code.encode()).hexdigest(),'exit_code':r.returncode,'stdout':r.stdout,'stderr':r.stderr,'sanitizers':['AddressSanitizer','UndefinedBehaviorSanitizer'],'scope':'Actual shutdown/open/close and native release on same controller with allocated buffers; lower power/handle/controller/subdev APIs modeled; native void shutdown/zero close and forced START/linked behavior retained, per-frame/CRM quiescence, remove and core/I-O/provider/hardware pending','device_modified':False};(out/'result.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2));raise SystemExit(r.returncode)
if __name__=='__main__':main()
