"""Actual actuator acquire/release pending cases, gate, helper and capture."""
from pathlib import Path
import hashlib,json,subprocess,importlib.util,re
BASE=Path('/mnt/wsl/PHYSICALDRIVE5p3/home/red_panda/RedPandaAndroid/pico4-pro');SOURCE=BASE/'source/phoenix-kernel-recovery';D='techpack/camera/drivers/cam_sensor_module/cam_actuator/'
NAMES=[D+n for n in ['cam_actuator_core.c','cam_actuator_dev.h','pico_actuator_acquire_unwind.inc','pico_actuator_acquire_unwind.h']]+['techpack/camera/drivers/cam_core/pico_camera_memento_capture.'+e for e in ['c','h']]+['techpack/camera/include/uapi/media/'+n for n in ['cam_defs.h','cam_sensor.h']]
def load(name):
    s=importlib.util.spec_from_file_location(name,Path(__file__).with_name(name+'.py'));m=importlib.util.module_from_spec(s);s.loader.exec_module(m);return m
MAIN=r'''
int main(void){
 struct cam_actuator_soc_private soc={0};struct cam_actuator_ctrl_t ctrl={.actuator_mutex={PTHREAD_MUTEX_INITIALIZER},.bridge_intf={-1,-1,-1,0},.soc_info={&soc,17}};expected_owner=&ctrl;struct cam_sensor_acquire_dev user={.session_handle=41};struct cam_control cmd={.op_code=CAM_ACQUIRE_DEV,.handle_type=CAM_HANDLE_USER_POINTER,.handle=(uintptr_t)&user};struct pico_memento_capture scope;
 input_error=1;assert(cam_actuator_driver_cmd(&ctrl,&cmd)==-EFAULT&&!creates&&!ctrl.pico_acquire_cleanup_pending&&ctrl.bridge_intf.device_hdl==-1);input_error=0;
 next_handle=-ENOMEM;watch=&scope;assert(!pico_memento_capture_begin(&scope,&ctrl,0x10009,CAM_ACQUIRE_DEV));assert(cam_actuator_driver_cmd(&ctrl,&cmd)==-ENOMEM);assert(!pico_memento_capture_end(&scope)&&scope.native_result==-ENOMEM&&!scope.side_effect&&!copies&&ctrl.bridge_intf.device_hdl==-1);
 watch=NULL;next_handle=0;assert(cam_actuator_driver_cmd(&ctrl,&cmd)==-EINVAL&&!copies&&!ctrl.pico_acquire_cleanup_pending);
 next_handle=1234;copy_error=1;watch=&scope;assert(!pico_memento_capture_begin(&scope,&ctrl,0x10009,CAM_ACQUIRE_DEV));assert(cam_actuator_driver_cmd(&ctrl,&cmd)==-EFAULT);assert(!pico_memento_capture_end(&scope)&&scope.unwound&&!scope.unwind_result&&!ctrl.pico_acquire_cleanup_pending&&ctrl.bridge_intf.device_hdl==-1&&ctrl.cam_act_state==CAM_ACTUATOR_INIT&&destroys==1);
 destroy_error=-EIO;assert(!pico_memento_capture_begin(&scope,&ctrl,0x10009,CAM_ACQUIRE_DEV));assert(cam_actuator_driver_cmd(&ctrl,&cmd)==-EFAULT);assert(!pico_memento_capture_end(&scope)&&!scope.unwound&&scope.unwind_result==-EIO&&ctrl.pico_acquire_cleanup_pending&&ctrl.bridge_intf.device_hdl==1234&&ctrl.cam_act_state==CAM_ACTUATOR_INIT);watch=NULL;
 unsigned before=creates;assert(cam_actuator_driver_cmd(&ctrl,&cmd)==-EINVAL&&creates==before);cmd.op_code=CAM_CONFIG_DEV;assert(cam_actuator_driver_cmd(&ctrl,&cmd)==-EBUSY&&!configs);cmd.op_code=CAM_START_DEV;assert(cam_actuator_driver_cmd(&ctrl,&cmd)==-EBUSY);
 struct cam_actuator_query_cap cap={0};cmd.op_code=CAM_QUERY_CAP;cmd.handle=(uintptr_t)&cap;copy_error=0;assert(!cam_actuator_driver_cmd(&ctrl,&cmd)&&cap.slot_info==17&&ctrl.pico_acquire_cleanup_pending);cmd.handle=(uintptr_t)&user;
 cmd.op_code=CAM_RELEASE_DEV;ctrl.bridge_intf.link_hdl=7;before=destroys;assert(cam_actuator_driver_cmd(&ctrl,&cmd)==-EAGAIN&&destroys==before&&ctrl.pico_acquire_cleanup_pending);ctrl.bridge_intf.link_hdl=-1;assert(cam_actuator_driver_cmd(&ctrl,&cmd)==-EIO&&ctrl.pico_acquire_cleanup_pending&&ctrl.bridge_intf.device_hdl==1234);
 destroy_error=0;assert(!cam_actuator_driver_cmd(&ctrl,&cmd)&&!ctrl.pico_acquire_cleanup_pending&&ctrl.bridge_intf.device_hdl==-1&&ctrl.bridge_intf.session_hdl==-1&&!powers);
 cmd.op_code=CAM_ACQUIRE_DEV;assert(!cam_actuator_driver_cmd(&ctrl,&cmd)&&ctrl.cam_act_state==CAM_ACTUATOR_ACQUIRE&&user.device_handle==1234);cmd.op_code=CAM_RELEASE_DEV;assert(!cam_actuator_driver_cmd(&ctrl,&cmd)&&ctrl.cam_act_state==CAM_ACTUATOR_INIT&&!powers);
 assert(!held&&list_empty(&pico_memento_captures));assert(!pthread_mutex_destroy(&ctrl.actuator_mutex.value));puts("PASS: actual actuator acquire/release cases and gate/helper/capture; positive copyin remainder, negative/zero create, copyout unwind, failed cleanup retained INIT, config/start/reacquire block, query allowed, linked/repeated release retry, ordinary success");
}
'''
def make_code(main_body=MAIN):
    peer=load('test-pico-peer-acquire-capture');common=load('test-pico-camera-hub-registry');core=(SOURCE/NAMES[0]).read_text();hdr=(SOURCE/NAMES[1]).read_text();states=re.search(r'enum cam_actuator_state \{.*?\n\};',hdr,re.S).group(0)
    prefix=common.HARNESS.split('/* OWNED_SUBDEVICE_MOCKS */')[0].replace('assert(!held);assert(!pthread_mutex_lock','assert(!pthread_mutex_lock').replace('assert(held==1);held--;','assert(held>0);held--;')
    mocks='\n'.join(l for l in peer.MOCKS.splitlines() if not l.startswith(('#define CAM_ACTUATOR_INIT ', '#define CAM_ACTUATOR_ACQUIRE ')))
    mocks=mocks.replace('static int copy_from_user(void *dst,const void *src,size_t n){memcpy(dst,src,n);return 0;}','static int input_error,destroy_error,power_error;static unsigned destroys,configs,powers;\nstatic int copy_from_user(void *dst,const void *src,size_t n){if(input_error)return 1;memcpy(dst,src,n);return 0;}').replace('assert(held==1 && n==24);if(watch)','assert(held==1);if(watch)').replace('static int cam_destroy_device_hdl(int handle){assert(held==1 && handle==1234);return 0;}','static int cam_destroy_device_hdl(int handle){assert(held==1&&handle==1234);destroys++;return destroy_error;}')
    types='struct cam_sensor_power_ctrl_t {void *power_setting,*power_down_setting;unsigned power_setting_size,power_down_setting_size;};struct cam_actuator_soc_private {struct cam_sensor_power_ctrl_t power_info;};struct cam_actuator_ctrl_t {struct mutex actuator_mutex;struct {int device_hdl,session_hdl,link_hdl,ops;}bridge_intf;struct {void *soc_private;int index;}soc_info;enum cam_actuator_state cam_act_state;bool pico_acquire_cleanup_pending,pico_release_cleanup_pending,pico_release_power_done,pico_core_powered,pico_io_initialized;unsigned last_flush_req;};\n'
    start=core.index('int32_t cam_actuator_driver_cmd(');switch=core.index('\tswitch (cmd->op_code)',start);acq=core.index('\tcase CAM_ACQUIRE_DEV:',switch);queryend=core.index('\tcase CAM_START_DEV:',acq)
    body=core[start:switch]+'\tswitch(cmd->op_code){\n'+core[acq:queryend]+'case CAM_CONFIG_DEV:configs++;break;default:rc=-EINVAL;break;}\nrelease_mutex:mutex_unlock(&a_ctrl->actuator_mutex);return rc;}\n'
    capture=(SOURCE/NAMES[4]).read_text();return '#include <stdint.h>\n#include <stddef.h>\n#include <string.h>\n#include <cam_defs.h>\n#include <cam_sensor.h>\n'+prefix+states+types+mocks+capture[capture.index('static DEFINE_MUTEX'):]+(SOURCE/NAMES[2]).read_text()+'static void pico_actuator_clear_requests_locked(struct cam_actuator_ctrl_t *c){assert(held==1);}\nstatic void kfree(void *p){assert(!p);}\nstatic int cam_actuator_power_down(struct cam_actuator_ctrl_t *c){powers++;return power_error;}\n'+body+main_body
def main():
    code=make_code()
    out=BASE/'out/phoenix-kernel-recovery/actuator-acquire-retry-tests';out.mkdir(exist_ok=True);(out/'harness.c').write_text(code)
    subprocess.run(['gcc','-std=gnu11','-g','-O1','-pthread','-fsanitize=address,undefined','-fno-omit-frame-pointer','-I'+str(SOURCE/'techpack/camera/include/uapi/media'),'-I'+str(SOURCE/'techpack/camera/include/uapi'),str(out/'harness.c'),'-o',str(out/'test')],check=True)
    r=subprocess.run([str(out/'test')],capture_output=True,text=True,timeout=10);report={'sources':{n:hashlib.sha256((SOURCE/n).read_bytes()).hexdigest() for n in NAMES},'harness_sha256':hashlib.sha256(code.encode()).hexdigest(),'exit_code':r.returncode,'stdout':r.stdout,'stderr':r.stderr,'sanitizers':['AddressSanitizer','UndefinedBehaviorSanitizer'],'scope':'Actual native command prefix/acquire/release/query cases, pending gate/helper/capture and native state/UAPI; create/destroy/usercopy/power/config APIs modeled; unmodeled start/stop bodies and ordinary release phases/shutdown/hardware pending','device_modified':False};(out/'result.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2));raise SystemExit(r.returncode)
if __name__=='__main__':main()
